# Generated by Django 4.0.4 on 2022-07-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Man'), (2, 'Woman'), (3, 'other')], null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfIntro',
            field=models.CharField(blank=True, max_length=252, null=True, verbose_name='selfIntro'),
        ),
    ]
